### ISSUE TITLE
Merge to List then Output as JSON: add as param?

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#292]
I believe this is a common pattern:
  - merge.to_list:
      input:
        - Brand
        - Part Codes
      output:  Match Inputs
      include_empty: true
  - convert.to_json:
      input: Match Inputs

I believe this is necessary when we are running Recipes in Excel, but I'm not certian.
Can we add something like?: output_format: with values as JSON and the default be a list.

**Comment by ChrisWRWX** [comment]
Closing this. There are a lot of different object manipulation wrangles now, and it seems to me it would be more confusing if we ended up with the option on some and not others, but adding to all adds a large amount of overhead to keep on top of.

While a little more verbose, using a separate wrangle seems more predictable, more testable and less likely to end up with bugs for edge cases.

This isn't necessary in Excel, it's done automatically there for anything returned to a sheet since Excel doesn't support python objects.

Happy to re-discuss in future.
