### ISSUE TITLE
Handling Column Names with Spaces (math and beyond...)

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#352]
It appears that columns referenced in the math wrangle can't have spaces. I know you devised a workaround for that as it relates to jinja templates.  _Can we figure out how to apply a solution globally so that user doesn't have to worry about spaces?_ For example, I think it's a problem when we do where clauses too.

**Comment by ChrisWRWX** [comment]
Broadly, anything python based uses underscores. This works for the python wrangle, jinja, custom functions. math doesn't have it at this time, needs adding.

where is an exception because it uses SQL syntax. For where you can use "", [] or `` (back tick). It would be nicer to be totally consistent, but they're dictated by the specific code being used.

@thomasstvr please will you check the docs to see if this is covered. Both wrangles.io and the schema.
