### ISSUE TITLE
Recipe Number format: handle errors with commas and underscores

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#361]
including a comma or underscore in a number causes errors that are hard to diagnose (eg column not found). I noticed it with batch_size but guessing it would happen wherever a 'bad' number is entered. Now that we have a universal interface for wrangles, can we catch those and either deal with it or alert the user?

And can we add it to the linting logic?

Also, let's add it to docs.

**Comment by ChrisWRWX** [comment]
This is largely specific to batch_size because it's a temporary fix (and hopefully going away sooner rather than later) and not part of the schema. This will already flag as an error if the place it's added doesn't allow strings. 

![image](https://github.com/wrangleworks/WranglesPY/assets/58178530/a0db6c27-a786-47f3-8590-75c88996f0aa)

Underscores behave as digit separators in yaml, so you can use those. This works:

![image](https://github.com/wrangleworks/WranglesPY/assets/58178530/6e4ea7cd-cddc-457d-a7f0-ef1fc63a38e9)

It looks like the library we're using for it in Excel doesn't actually recognize that though, so unfortunately flags them as errors even though they work. It isn't an option by the looks of it, just a deficiency in their implementation of the standard, so not something we can fix. It's actually the same in VSCode (fairly sure we're using the same library).
