### ISSUE TITLE
Where Filtering with exract.custom

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#516]
When using a where filter with extract.custom, if the where sends an empty batch it causes a break. 

Would be good to catch empty batches, before sending the data to the wrangle.

**Comment by v2ngu** [comment]
There are two different types of wrangles:

- returns a modified df (NOT similar len rows)
The ones that return a modified df are skipped over due to no_where_list


-returned rows are the SAME length.
Need to continue for the wrangles that are same length. They should skip the entire wrangle because there are no rows in that dataframe and thus no wrangle should be performed for each row. 

Write test cases for multi-wrangle recipes (where there should be a where clause that returns no rows).
