### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPy#75]
It would be nice to be able to assign aliases to columns in order to use them for things like matching without having to create a copy or rename the column. Creating a copy can cause clutter and renaming can lose meaning at times.

**Comment by ChrisWRWX** [comment]
Closing this. I think aliases might add more confusion by having the same entity be referenced in multiple ways rather than being consistent.

Matching is currently hard-coded with specific required fields but should be altered to allow the user to specify the input flexibly in future, so I don't think it is a good example.

Feel free to re-open in future with a specific plan for implementation.
